### ISSUE TITLE
No achieve found 

### ISSUE THREAD

**Issue by felixerdy** [sensebox/openSenseMap-API#70]
When opening the archieve for https://opensensemap.org/explore/5710de1a45fd40c8198ccece, no archive can be found (404). Maybe due to the letter ü in the senseBox name?

**Comment by mpfeil** [comment]
The archive link is created in the frontend [archiveLink](https://github.com/sensebox/openSenseMap/blob/6f9b7097cd2531c3f7769e1fca41f7ec19ff8be9/app/scripts/controllers/sidebar.boxdetails.js#L36)

The [archive script](https://github.com/sensebox/osem-archiver) replaces german umlauts with two `__` (underscores). The frontend just replace it with one `_` (underscore).

Example:
archiver: https://archive.opensensemap.org/2017-02-24/5710de1a45fd40c8198ccece-S__dkirchen/
frontend: https://archive.opensensemap.org/2017-02-24/5710de1a45fd40c8198ccece-S_dkirchen

Will be fixed in the frontend.
